version: "3.8"

# Network jdidd
networks:
  streaming-network:
    driver: bridge

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - streaming-network

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - streaming-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - streaming-network

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    volumes:
      - cassandra-data:/var/lib/cassandra
    networks:
      - streaming-network

  app:
    image: streaming-app
    depends_on:
      - kafka
      - mongodb
      - cassandra
    ports:
      - "8501:8501"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MONGO_URI=mongodb://mongodb:27017/
      - CASSANDRA_HOST=cassandra
      - PYTHONUNBUFFERED=1
    volumes:
      - ./:/app
    command: tail -f /dev/null
    networks:
      - streaming-network

volumes:
  cassandra-data: